### ISSUE TITLE
When importing a dangerfile from git, the inline messages are not shown

### ISSUE THREAD

**Issue by daniel-beard** [danger/danger#1010]
# Report

## What did you do?

My danger setup has a single shared base Dangerfile, that's imported like this:

```
danger.import_dangerfile(github: 'mobile/danger')
```

I then have some shared rules that run entirely within the shared Dangerfile. However, the file/line comments for both warn and fail actions do not post inline in the PR.

All I get is this:

<img width="782" alt="screen shot 2018-08-14 at 1 27 46 pm" src="https://user-images.githubusercontent.com/2645146/44116734-2cbd08b8-9fc6-11e8-96ae-f3d0406dcec4.png">

I have double checked that both the filename and line number appear to be correct:

<img width="448" alt="screen shot 2018-08-14 at 1 42 30 pm" src="https://user-images.githubusercontent.com/2645146/44117383-010de488-9fc8-11e8-994c-e2595e06c7ec.png">

<img width="527" alt="screen shot 2018-08-14 at 1 42 36 pm" src="https://user-images.githubusercontent.com/2645146/44117394-04b5e5f4-9fc8-11e8-99d3-4ae34ea9a1b7.png">

## What did you expect to happen?

Running a rule implemented in a dangerfile that's imported via git should be able to post inline messages to the original commit.

## What happened instead?

Only posted the "summary" message.

## Your Environment

* Which CI are you running on?
  * Jenkins
* Are you running the latest version of Danger?
  * 5.5.11

**Comment by AliSoftware** [comment]
@daniel-beard Danger only support inline comments on GitHub & GitHub EE.

So if you're using GitLab, BitBucket or VSTS, inline comments haven't been implemented yet (i'm guessing either because of lack of time by the contributors of Danger or because the API of those don't support inline comments yet)

See [the table "FEATURES" in the documentation](https://danger.systems/ruby/#features)

Depending on what Git hosting system you're using, there are issues tracking support for inline comments for each, e.g. #522 for support of those inline comments in GitLab.

**Comment by daniel-beard** [comment]
It is Github EE, it works when NOT importing via git, however it appears that any imported rules via the git import action do not comment inline, rather just in the single combined comment.

**Comment by daniel-beard** [comment]
Possibly related to #1042
