### ISSUE TITLE
Run danger from subdirectory

### ISSUE THREAD

**Issue by scranen** [danger/danger#1177]
I'd basically like to re-open #219, for the following reason. We are trying to set up a build in a mono repo, where each project might have its own Dangerfile, or even no Dangerfile at all. We'd like each Dangerfile to be able to assume that it is in the root of the project, so in the following diagram, we want to run `danger` from `./project1`, rather than from `.`.
```
.
├── .git
├── project1
│     ├── Dangerfile
│     ┆
│     └── ...
└── project2
      ├── Dangerfile
      ┆
      └── ...
```

**Current behaviour**
Running `danger` in a subdirectory of a git repository results in an error like the following:
```
/path/to/repo/project1/.git: path does not exist (ArgumentError)
```

**Desired behaviour**
Running `danger` in a subdirectory of a git repository just looks up the root of the git repository itself.

**Suggested fix**
It seems that the fix suggested in #219 actually does work: changing
```diff
     def diff_for_folder(folder, from: "master", to: "HEAD")
       self.folder = folder
-      repo = Git.open self.folder
+      repo = Git.open exec("rev-parse --show-toplevel")

       ensure_commitish_exists!(from)
       ensure_commitish_exists!(to)

       merge_base = find_merge_base(repo, from, to)
       commits_in_branch_count = commits_in_branch_count(from, to)

-      self.diff = repo.diff(merge_base, to)
+      self.diff = repo.diff(merge_base, to).path(folder)
       self.log = repo.log(commits_in_branch_count).between(from, to)
     end
```
in `/lib/danger/scm_source/git_repo.rb` seems to do the trick.

**Comment by orta** [comment]
I feel slightly wary that this could break someone's setup if they had already introduced danger using a pattern like the original fix of `--dangerfile` - so if it can be done behind a flag somehow, I'm game 👍

**Comment by scranen** [comment]
I've limited the scope of the change to the only place that I think is currently triggering the issue by making the lookup behaviour explicit in the interface of `GitRepo`. I added tests for `GitRepo`, but would appreciate if someone could help me to get a test in place for actually calling danger itself from a subdirectory. (Current test shows that `GitRepo` can deal with being called from a subfolder, but not that calling `danger` from a subfolder would work as expected)

**Comment by scranen** [comment]
I also changed my mind on the additional `.path(folder)` in the diff I posted previously. On second thought I think this filtering should be left up to the user if they want it.

**Comment by scranen** [comment]
@orta do you know when we can expect the new version on rubygems.org? (I'd like to decide if I should refer to the tag on Github in my Gemfile or if I can wait for the new version being available.)

**Comment by orta** [comment]
Already shipped: https://github.com/danger/danger/pull/1178#issuecomment-576728605

**Comment by Stephan202** [comment]
@orta I think @scranen's question is about when it'll show up [here](https://rubygems.org/gems/danger/versions).

**Comment by orta** [comment]
argh, OTP on rubygems meant it didn't send

**Comment by orta** [comment]
Alright, there we go - thanks for the poke

**Comment by Skoti** [comment]
Assume
```
.
├── .git
├── nested
│     ├── nested-again
│       ├── Dangerfile

```
When executing `danger` from `nested-again` directory the paths returned by `git.renamed_files`, `git.modified_files` and `git.added_files` are incorrect. They will all start with `/nested/nested-again/someFilename` instead of just `./someFilename` as this is the **current** working directory.

This leads to issues in all plugins as most of them is doing `File.expand_path` on the returned paths and the final path is:
`/Users/<username>/<path_to_repo>/nested/nestedAgain/nested/nestedAgain/someFilename` leading to:
 `(No such file or directory)` errors.

I don't know where is the root cause but it seems like the change to make `danger` run in a _subdirectory_ is not completed.
Would you please take a look at this?

Example of an issue in swiftlint plugin:
https://github.com/ashfurrow/danger-ruby-swiftlint/issues/175

**Comment by jasonzurita** [comment]
Just ran into the same issue noted by @Skoti. I am not that familiar with the inner workings of `danger`, but is there a way where we can specify the directory that `danger` is running in?

**Comment by Del-S** [comment]
I ran into this (or similar) issue myself today. We run danger in root folder of the project: `danger --danger_id=lint_danger --dangerfile=config/danger/Dangerfile --remove-previous-comments --verbose` with config in different directory and it breaks inline comments for plugins.

When I move `Dangerfile` into root and remove `--dangerfile` from the command it works properly. So that is the workaround for me at the moment.
