### ISSUE TITLE
Rename diff-related methods

### ISSUE THREAD

**Issue by jeroenvisser101** [danger/danger#137]
To stick with the 'code should be readable by humans' part of ruby/rails, I guess it would be cool if we could rename these attributes in the DSL (and create aliases for BC?)

| Old argument | New argument |
| --------- | ------- |
| `files_deleted` | `deleted_files` |
| `files_modified` | `modified_files` |
| `files_added` | `added_files` |

Any thoughts about this? Is this an important enough change to compromise on BC?

**Comment by orta** [comment]
I don't care about BC till [post-1.0](https://github.com/danger/danger/milestones/1.0.0) - but to the point. 

I originally went with `files_` in order to have them consistent with each other, I don't have a strong opinion on it though, so I am totally cool with changing if you can give me some examples of where other libs do it as `xxx_files`

**Comment by jeroenvisser101** [comment]
I couldn't find any libs doing this, and also don't have a strong opinion on this, but I was thinking the latter would possibly ease reading a bit:

``` ruby
if deleted_files.include?('path/to/file')
  # ...
end
```
vs.
``` ruby
if files_deleted.include?('path/to/file')
  # ...
end
```

**Comment by orta** [comment]
I agree 👍🏾 - let's do it.
