### ISSUE TITLE
Support for other code collaboration services than GitHub.

### ISSUE THREAD

**Issue by justMaku** [danger/danger#213]
Hi there!

As much as I love GitHub, sometimes I have to use other services like BitBucket or GitLab and unfortunately Danger doesn't support these at this moment. I took a look at the source code and even though everything is made in a modular fashion, some parts of the Danger are depending on some GitHub features and changing that might break some already existing plugins/workflows that people are using. 

Some of the issues I've already found with the current implementation:

* Some of the CI sources require either an GitHub specific environment variable or a GitHub git origin. 
* Some of the CI's that Danger supports might also not support a pull request provider other than GitHub
* EnvironmentManager uses a specific GitHub feature to get the merged PR's branch. 

There's probably more that I'm not aware of though.

I'm more than happy to contribute a solution to allow BitBucket support, but before I start working on it, I'd rather hear your opinion on how could we approach this issue in the best manner.

**Comment by orta** [comment]
I'm totally for multiple request source types, e.g. https://github.com/danger/danger/pull/59 

Building it out will be tricky aye, I don't doubt that, but it's definitely doable, and definitely something I want to see happen.

Realistically every project I've worked on ( and all the other main contributors ) is GitHub, so we've definitely got lazy here and there with making it easy to support more request sources.

> * Some of the CI sources require either an GitHub specific environment variable or a GitHub git origin. 

Aye, I bet that can be improved upon, perhaps a CI source can have the chance to reject a request source? Or try to make the `[user]/[repo]` thing more generic

> * Some of the CI's that Danger supports might also not support a pull request provider other than GitHub

Perhaps the CI 

> * EnvironmentManager uses a specific GitHub feature to get the merged PR's branch. 

This is a fallback, generally, and something I'd like to address, it can be _really_ tricky to actually get the commit range for the current code review. ( Mainly due to local CI caching ) 

We're also seeing that there might not be APIs that are used in GitHub that are on other request sources ( which is what delayed GitLab support ) - so that might be another gotcha.

**Comment by orta** [comment]
At least Danger is well tested, so in making those changes, someone can be pretty sure they're not breaking existing stuff too much 👍

**Comment by justMaku** [comment]
> > * EnvironmentManager uses a specific GitHub feature to get the merged PR's branch.

>This is a fallback, generally, and something I'd like to address, it can be really tricky to actually get the commit range for the current code review. ( Mainly due to local CI caching )

I started looking more into the code and I don't really understand why Danger requires this fetch. But I'm not a git expert so if you could explain it to me I'd be grateful.

**Comment by orta** [comment]
The tough thing here is knowing what the start/end commits refer to, as you can't make any guarantees that the local CI either has the commit range, or that the current git head is within that range, so Danger makes her own branches for base and head. 

I could use a feature of GitHub to simplify making the head reference ( e.g. the latest commit on a PR ) so I did, I am alright with using the API's metadata to commit. 

Note that as test can take some time to build, the :head commit after the initial clone could be `abdee` but in that time, more commits could have been pushed, so the gh/bb API metadata could refer to commits that are not yet fetched because they were pushed during the testing process.

( note be wary #218 makes some pretty drastic structural changes, but shouldn't necessarily affect these bits of code, should get merged today )

**Comment by orta** [comment]
Cool, I can wait on merging my PR ( so I can deal with the pains of the conflicts ;)

**Comment by justMaku** [comment]
@orta I'm nowhere close to finishing, so don't wait for my changes and merge whenever your code is ready :)

**Comment by justMaku** [comment]
Correct me if I'm wrong (and I probably am), but doesn't it actually make things worse? 

By using the metadata from GitHub API Danger might actually "parse" code that doesn't correspond to the given CI task. Given your example, I could ask danger to work on PR with range of A1..B9 and during the build/test phase rebase and force push it with different base and head. This would make Danger to operate on a different code base than the rest of the build process did.

Again, I'm not an expert on this matter, but in my opinion it's a safe assumption to make that the build server has all the commits required to build a given CI task and that CI does already runs on the HEAD of the tested branch (and if that's not true, all of CI's supported by Danger do provide that information in the environment variables)

**Comment by orta** [comment]
I'm on board with not trying to always make it use the PR's true HEAD, but the commit that triggered the build 👍 

Due to #226 - Danger can't always know where to get the beginning of a PR, it's the base which gets a bit tricky.

I wouldn't be adverse to simplifying there. Some of these bits feel quite arcane, and I'd love to see them reduced in size/scope. Danger doing less messing around in both Git & GitHub is definitely a positive.

**Comment by connorshea** [comment]
Can we close this now that GitLab support is included? :)

**Comment by orta** [comment]
Yes!

**Comment by justMaku** [comment]
<3
