### ISSUE TITLE
Customize the merge branch 

### ISSUE THREAD

**Issue by marcelofabri** [danger/danger#51]
Today, danger only runs on PRs against `master` (at least the README says so).

It'd be awesome to be able to customize the merge branch. We, for example, keep a shipped version on master and all the development goes on a `development` branch.

I can try to take a look at this, but it seems it should be easy. Unless I'm missing something, only two places uses `master` hardcoded (https://github.com/danger/danger/blob/master/lib/danger/ci_source/buildkite.rb#L20 and https://github.com/danger/danger/blob/df58dcbad790cc14010fe1343e9511fce206597a/lib/danger/scm_source/git_repo.rb#L9). 

I think one important question is where this branch would be specified: on the `Dangerfile` (if so, this probably would be harder because it seems that the file actually is run) or as a command line parameter.

**Comment by orta** [comment]
This is in with #46 

It actually is pretty smart about this, depending on your CI provider. It depends on what it exposes as ENV vars, as you spotted. 

TBH though, I think we'd need to do more. Danger needs to have a access to the origin's merge branch for the base and a remote branch for a fork maybe. I think the fork would be what the CI runs on, so it needs to be able to pull the origin if needed. Making the process more like:

* Find out what CI it's on
* Find out the PR number
* Grab PR metadata
* Look inside PR JSON for the commit range
* Check if the remotes are the same, otherwise ensure that we have the full commit range
* Now Danger can grab the full PR's commits to do git checking on

**Comment by marcelofabri** [comment]
I'm kind of lost on what's done and what's not. What would be the next steps (and how I could help)?

**Comment by orta** [comment]
Done:

* ~~Find out what CI it's on~~
* ~~Find out the PR number~~
* ~~Grab PR metadata~~
* Look inside PR JSON for the commit range
* Check if the remotes are the same, otherwise ensure that we have the full commit range
* Now Danger can grab the full PR's commits to do git checking on

The logic around deciding what the commit range to choose should move from the CI Source to the request source (GitHub from the CI.) The CI source should only exist to help the request  _find_ the PR to look at. Then all commit range data can come from the PR's canonical JSON.

**Comment by marcelofabri** [comment]
@orta moving to request source wouldn't make #45 happen again? If there's no `CI_PULL_REQUEST` set, there's (apparently) no way to get the PR.

**Comment by marcelofabri** [comment]
I've started this on #53 but I'm not sure why "Check if the remotes are the same, otherwise ensure that we have the full commit range" is needed and how we would do that.

**Comment by orta** [comment]
In travis when comparing [mine](https://travis-ci.org/danger/danger/builds/108232117)  to [yours](https://travis-ci.org/danger/danger/builds/108233807). I get env vars, they must only be set when it's coming from the host repo. 

It looks like the only option is to include it as a public env var, which comes with it's own tradeoffs really.

**Comment by marcelofabri** [comment]
Was this comment meant to be on #52? :sweat_smile: 

(And linking to [this](https://travis-ci.org/danger/danger/builds/108468410) when you said "yours"?)

**Comment by orta** [comment]
it was :D

**Comment by orta** [comment]
I think, that this in part will relate to #88

**Comment by orta** [comment]
Runner has this; 

```
    def self.options
      [
        ['--base=[master|dev|stable]', 'A branch/tag/commit to use as the base of the diff'],
        ['--head=[master|dev|stable]', 'A branch/tag/commit to use as the head']
      ].concat(super)
    end
```
