### ISSUE TITLE
`danger pr` doesn't respect env variables, unable to use with GH Enterprise

### ISSUE THREAD

**Issue by mtitolo** [danger/danger#691]
# Report

## What did you do?
`danger pr https://internalgithub.website.com/org/repo/pulls/111`

## What did you expect to happen?
I expected `danger pr` to use `DANGER_GITHUB_API_HOST` to figure out what url to hit

## What happened instead?

It used `api.github.com` which does not work for GH enterprise instances.

```
/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/org/repo/pulls/287: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)]
```

## Your Environment

Danger 4.0.4, ruby 2.3.0

**Comment by orta** [comment]
@dbgrandi feel like doing some ruby again? ^

**Comment by JuanitoFatas** [comment]
Hi @mtitolo,

Sorry for your troubles. Thanks for the report, a fix is ready in #697.

Also I have a question about your PR url.

danger look at your PR url to infer the repository. Current [our regexp](https://github.com/danger/danger/blob/master/lib/danger/ci_source/support/find_repo_info_from_url.rb#L7) can only find the repo from:

`https://internalgithub.website.com/org/repo/pull/111`

instead of

`https://internalgithub.website.com/org/repo/pulls/111`

Does GitHub Enterprise use `pulls` instead of `pull` in PR url?

Thanks,
Juanito

**Comment by mtitolo** [comment]
@JuanitoFatas the `pull` URL is the API. Should the endpoint passed to `local` be the HTML URL or the API?

**Comment by JuanitoFatas** [comment]
> @JuanitoFatas the pull URL is the API. Should the endpoint passed to local be the HTML URL or the API?

Should be the HTML URL. 

The HTML URL should be `pull`? `https://github.com/danger/danger/pull/697`
