### ISSUE TITLE
Q: what message() arguments is doing?

### ISSUE THREAD

**Issue by php-coder** [danger/danger#741]
I couldn't find what exactly `line` and `file` arguments are doing? When I'm specifying them, a messages doesn't get changed. So why I would use them?

**Comment by orta** [comment]
They are for when you want to associate a message to a specific file/line, and then Danger will comment inside the diff instead of in a comment on the PR. Those file/lines have to be inside the diff though, or it will fall back to the main comment. [CHANGLOG note](https://github.com/danger/danger/blob/master/CHANGELOG.md#320)

**Comment by php-coder** [comment]
Could you update the documentation (http://danger.systems/reference.html) and clarify this moment?

**Comment by orta** [comment]
Hrm, there is an example on that section, but a bit more docs can't hurt 👍  - will be shipped in the next danger release.
